### ISSUE TITLE
Plain text output

### ISSUE THREAD

**Issue by ryuran** [jabney/render-template-loader#4]
I try to make it work with `html-loader` but the output should be a plain-text html and not a js with a exported string.
Maybe add an option for output mode.
I can't find a loader "string to plain text"

**Comment by ryuran** [comment]
I close this one by using `extract-loader`.

Maybe we could add an exemple using `html-loader`.

**Comment by jabney** [comment]
One of [the examples](https://github.com/jabney/render-template-loader#render-pagehtml-from-a-pug-template) from the readme uses `extract-loader`. I don't remember why it's used in this specific example and not the others (I originally developed this loader a couple years ago).

```javascript
module.exports = {
  entry: './src/index.js',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [{
      test: /\.pug$/,
      use: [{
        loader: 'file-loader?name=[name].html'
      },
      {
        loader: 'extract-loader'
      },
      {
        loader: 'render-template-loader',
        options: {
          engine: 'pug',
          locals: {
            title: 'Rendered with Pug!',
            desc: 'Partials Support'
          },
          engineOptions: function (info) {
            return { filename: info.filename }
          }
        }
      }]
    }]
  },
  plugins: []
}
```

It may be because of the `file-loader` item used higher in the loader stack, or it may be that `HtmlWebpackPlugin` used in the [other examples](https://github.com/jabney/render-template-loader#render-indexhtml-from-an-ejs-template) likes a module export:

```javascript
module.exports = {
  entry: './src/index.js',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [{
      test: /\/src\/index.ejs$/,
      use: [{
        loader: 'render-template-loader',
        options: {
          engine: 'ejs',
          locals: {
            title: 'Render Template Loader',
            desc: 'Rendering templates with a Webpack loader since 2017'
          },
          engineOptions: function (info) {
            // Ejs wants the template filename for partials rendering.
            // (Configuring a "views" option can also be done.)
            return { filename: info.filename }
          }
        }
      }]
    }]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.ejs'
    })
  ]
}
```

Perhaps `html-loader` behaves like `file-loader` and likes a plain text file, whereas when using `HtmlWebpackPlugin` extraction isn't necessary.

From the [documentation on extract-loader](https://webpack.js.org/loaders/extract-loader/):

> The extract-loader evaluates the given source code on the fly and returns the result as string. Its main use-case is to resolve urls within HTML and CSS coming from their respective loaders. Use the file-loader to emit the extract-loader's result as separate file.

```javascript
import stylesheetUrl from "file-loader!extract-loader!css-loader!main.css";
// stylesheetUrl will now be the hashed url to the final stylesheet
```

> The extract-loader works similar to the extract-text-webpack-plugin and the mini-css-extract-plugin and is meant as a lean alternative to it. When evaluating the source code, it provides a fake context which was especially designed to cope with the code generated by the html- or the css-loader. Thus it might not work in other situations.

I'll consider how this might be documented perhaps in a FAQ. If you want, post the webpack config you're using so I can have a look.

**Comment by ryuran** [comment]
Yes.

`html-loader` want a plain text file as input and give a js exporting a string as output.
`HtmlWebpackPlugin` can work with a js exporting a `string` or a template function as entry.

So if you want chain with `html-loader` to resolve `img` or other assets files, you need to use `extract-loader` as middleware.

**Comment by jabney** [comment]
Added a [FAQ](https://github.com/jabney/render-template-loader#faq) section in `1.2.1` that provides some explanation on `extract-loader`.
